name: Build ASP.NET Core API

on:
  pull_request:
    branches:
      - develop

  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore Packages
        run: dotnet restore

      - name: Build Application
        run: dotnet build --no-restore

      - name: Run Tests
        run: dotnet test VinAgent.Tests/VinAgent.Tests.csproj --no-build

      # Dependency Vulnerability Scan
      - name: Dependency Vulnerability Scan
        run: |
          dotnet list package --vulnerable --include-transitive

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t vehicleapi:${{ github.sha }} .

      # Docker Image Scan
      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@v0.35.0
        with:
          scan-type: image
          image-ref: vehicleapi:${{ github.sha }}
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0

      # Login to Azure only after merge to develop
      - name: Login to Azure
        if: github.event_name == 'push'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Show Azure Context
      if: github.event_name == 'push'
      run: |
        az account show \
          --query "{subscription:name,subscriptionId:id,tenantId:tenantId}" \
          -o table

    - name: Show ACR
      if: github.event_name == 'push'
      run: |
        az acr show \
          --name edata \
          --query "{name:name,id:id,loginServer:loginServer,resourceGroup:resourceGroup}" \
          -o table

      # Login to ACR only after merge to develop
      - name: Login to ACR
        if: github.event_name == 'push'
        run: |
          az acr login --name edata

      # Tag Docker Image
      - name: Tag Docker Image
        if: github.event_name == 'push'
        run: |
          docker tag vehicleapi:${{ github.sha }} \
            edata.azurecr.io/vehicleapi:${{ github.sha }}

      # Push Docker Image
      - name: Push Docker Image
        if: github.event_name == 'push'
        run: |
          docker push edata.azurecr.io/vehicleapi:${{ github.sha }}