name: Deploy QA

on:
  workflow_run:
    workflows:
      - Build ASP.NET Core API  
    types:
      - completed
    branches:
      - develop

jobs:
  deploy-qa:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    environment: QA

    steps:
    
      # Checkout the exact source commit that was built
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      # Setup .NET for integration tests
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      
      # Login to Azure      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Show Azure Context
        run: |
          az account show \
            --query "{subscription:name,subscriptionId:id,tenantId:tenantId}" \
            -o table

      - name: Show ACR
        run: |
          az acr show \
            --name edata \
            --query "{name:name,id:id,loginServer:loginServer}" \
            -o table
      
      # Deploy the exact image created by Build
      - name: Deploy Image to QA Slot
        uses: azure/webapps-deploy@v3
        with:
          app-name: vinagent-api
          slot-name: qa
          images: edata.azurecr.io/vehicleapi:${{ github.event.workflow_run.head_sha }}

      # Health Check
      - name: Health Check
        run: |
          echo "Waiting for QA application to start..."
          sleep 20

          echo "Checking QA health endpoint..."

          curl --fail \
            --retry 10 \
            --retry-delay 10 \
            --retry-all-errors \
            https://vinagent-api-qa-e0fjdzd7bggtafdq.westeurope-01.azurewebsites.net/health

          echo "QA Health Check passed."

      # Smoke Test
      - name: Smoke Test QA API
        run: |
          URL="https://vinagent-api-qa-e0fjdzd7bggtafdq.westeurope-01.azurewebsites.net/Vin/DetailsByVIN?vin=JTJBM7FX4A5005889"

          echo "Running smoke test..."

          STATUS=$(curl -s -o response.json -w "%{http_code}" "$URL")

          echo "HTTP Status: $STATUS"
          cat response.json

          if [ "$STATUS" -ne 200 ]; then
            echo "Smoke test failed."
            exit 1
          fi

          echo "Smoke test passed."
      
      # API Integration Test      
      - name: API Integration Test
        env:
          API_BASE_URL: https://vinagent-api-qa-e0fjdzd7bggtafdq.westeurope-01.azurewebsites.net
        run: |
          dotnet test IntegrationTests/IntegrationTests.csproj \
            --configuration Release          